version: "3.9"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - "./redis:/data"
    command: "redis-server --save 1 1 --loglevel warning --maxmemory-policy noeviction"
  postgres:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    volumes:
      - "./postgres:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_PASSWORD=password"
